project:
  type: website

website:
  title: "ISSS608-Liu Chih Yuan"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        
  sidebar:        # ← change from `navbar:` to `sidebar:`
    style: "floating"
    contents:
      - section: "Hands-on Exercise"
        contents:
          - text: "Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: "Exercise 3"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd
      - section: "Session Notes"
        contents:
          - text: "Session 1"
            href: Session_notes/session_notes1.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

