project:
  type: website

website:
  title: "ISSS608-Liu Chih Yuan"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        
  sidebar:        # ← change from `navbar:` to `sidebar:`
    style: "floating"
    contents:
      - section: "Hands-on Exercise"
        contents:
          - text: "Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: "Exercise 3A"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd
          - text: "Exercise 3B"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.qmd
          - text: "Exercise 4A"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.qmd
          - text: "Exercise 4B"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.qmd
          - text: "Exercise 4C"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.qmd
          - text: "Exercise 4D"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.qmd
          - text: "Exercise 5"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd
          - text: "Exercise 6"
            href: Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.qmd
          - text: "Exercise 8A"
            href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07_1.qmd
          - text: "Exercise 8B"
            href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07_2.qmd
          - text: "Exercise 8C"
            href: Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07_3.qmd
          - text: "Exercise 9A"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex09a.html
          - text: "Exercise 9B"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex09b.html
          - text: "Exercise 9C"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex09c.html   
          - text: "Exercise 9D"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex09d.html
          - text: "Exercise 9E"
            href: Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex09e.html     
      - section: "Take-Home Exercise"
        contents:
          - text: "Take-Home Ex01 A"
            href: TakeHome_Ex/TakeHome_Ex01/TakeHome_Ex01.qmd
          - text: "Take-Home Ex01 B"
            href: TakeHome_Ex/TakeHome_Ex01/TakeHome_Ex01B.qmd
          - text: "Take-Home Ex02 A"
            href: TakeHome_Ex/TakeHome_Ex02/TakeHome_Ex02.qmd
          - text: "Take-Home Ex03"
            href: TakeHome_Ex/TakeHome_Ex03/TakeHome_Ex03.qmd
      - section: "In Class Exercise"
        contents:
          - text: "Week 5 In Class Exercise"
            href: MC1/MC1_InClass.qmd
      - section: "Testing Section"
        contents:
          - text: "For project"
            href: testing_qmd/main.qmd
          
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

