project:
  type: website

website:
  title: "ISSS608-Liu Chih Yuan"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        
  sidebar:        # ← change from `navbar:` to `sidebar:`
    style: "floating"
    contents:
      - section: "Hands-on Exercise"
        contents:
          - text: "Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: "Exercise 3a"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.qmd
          - text: "Exercise 3b"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03_2.qmd
          - text: "Exercise 4a"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_1.qmd
          - text: "Exercise 4b"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_2.qmd
          - text: "Exercise 4c"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_3.qmd
          - text: "Exercise 4d"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04_4.qmd
          - text: "Exercise 5"
            href: Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.qmd
      - section: "Session Notes"
        contents:
          - text: "Session 1"
            href: Session_notes/session_notes1.qmd
      - section: "Take-Home Exercise"
        contents:
          - text: "Take-Home Ex01 A"
            href: TakeHome_Ex/TakeHome_Ex01/TakeHome_Ex01.qmd
          - text: "Take-Home Ex01 B"
            href: TakeHome_Ex/TakeHome_Ex01/TakeHome_Ex01B.qmd
      - section: "In Class Exercise"
        contents:
          - text: "Week 5"
            href: MC1/MC1_InClass.qmd
          
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

